## 1.数组创建

可以使用array函数从常规Python**列表或元组**中创建数组。得到的数组的类型是从Python列表中元素的类型推导出来的。

创建数组最简单的办法就是使用array函数。它接受一切序列型的对象（包括其他数组），然后产生一个新的含有传入数据的numpy数组。其中，嵌套序列（比如由一组等长列表组成的列表）将会被转换为一个多维数组

In [1]:
import numpy as np

#将列表转换为数组
array = np.array([[1,2,3],
                 [4,5,6]])
print(array)

[[1 2 3]
 [4 5 6]]


In [2]:
import numpy as np

#将元组转换为数组
array = np.array(((1,2,3),
                 (4,5,6)))
print(array)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np

a = np.array((1,2,3,4)) 
print(a)

[1 2 3 4]


In [4]:
array = np.arange( 10, 31, 6 )
print(array)

[10 16 22 28]


In [5]:
array =  np.arange(3,6)
print(array)

[3 4 5]


In [6]:

array = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(array)
#数组维度
print(array.ndim)
#数组形状
print(array.shape)
#数组元素个数
print(array.size)
#数组元素类型
print(array.dtype)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)
12
int32


In [7]:

array1 = np.arange(6).reshape([2,3])
print(array1)

array2 = np.array([[1,2,3],[4,5,6]],dtype=np.int64).reshape([3,2])
print(array2)


[[0 1 2]
 [3 4 5]]
[[1 2]
 [3 4]
 [5 6]]


## 2.数组的计算

数组很重要，因为它可以使我们不用编写循环即可对数据执行批量运算。这通常叫做矢量化（vectorization）。

**大小相等的数组之间的任何算术运算都会将运算应用到元素级**。同样，数组与标量的算术运算也会将那个标量值传播到各个元素.


In [8]:

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.ones([2,3],dtype=np.int64)

print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)
print(arr1 ** 2)


[[2 3 4]
 [5 6 7]]
[[0 1 2]
 [3 4 5]]
[[1 2 3]
 [4 5 6]]
[[1. 2. 3.]
 [4. 5. 6.]]
[[ 1  4  9]
 [16 25 36]]


In [9]:
#矩阵乘法
arr3 = np.array([[1,2,3],[4,5,6]])
arr4 = np.ones([3,2],dtype=np.int64)
print(arr3)
print(arr4)
print(np.dot(arr3,arr4))

[[1 2 3]
 [4 5 6]]
[[1 1]
 [1 1]
 [1 1]]
[[ 6  6]
 [15 15]]


In [10]:
print(arr3)
print(np.sum(arr3,axis=1)) #axis=1,每一行求和 axie=0,每一列求和
print(np.max(arr3))
print(np.min(arr3))
print(np.mean(arr3))
print(np.argmax(arr3))
print(np.argmin(arr3))

[[1 2 3]
 [4 5 6]]
[ 6 15]
6
1
3.5
5
0


In [11]:
arr3_tran = arr3.transpose()
print(arr3_tran)

print(arr3.flatten())

[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]


## 3.数组的索引与切片

In [ ]:
arr5 = np.arange(0,6).reshape([2,3])
print(arr5)
print(arr5[1])
print(arr5[1][2])

print(arr5[1,2])

print(arr5[1,:])
print(arr5[:,1])
print(arr5[1,0:2])

# Pandas库

pandas是python第三方库，提供高性能易用数据类型和分析工具。

pandas基于numpy实现，常与numpy和matplotlib一同使用

更多学习，请参考**pandas中文网**：https://www.pypandas.cn/



## 1.Series

Series是一种类似于一维数组的对象，它由一维数组（各种numpy数据类型）以及一组与之相关的数据标签（即索引）组成.

可理解为带标签的一维数组，可存储整数、浮点数、字符串、Python 对象等类型的数据。

In [12]:
import pandas as pd
import numpy as np

s = pd.Series(['a','b','c','d','e'])
print(s)

0    a
1    b
2    c
3    d
4    e
dtype: object


In [ ]:
#与字典不同的是：Series允许索引重复
s = pd.Series(['a','b','c','d','e'],index=[100,200,100,400,500])
print(s)
